spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:tacodb
    username: sa
    password:
  h2:
    console:
      settings:
        web-allow-others: true
      path: /h2
      enabled: true
  sql:
    init:
      data-locations: classpath*:data.sql
      schema-locations: classpath*:schema.sql
      mode: always