server:
  port: 8080

logging:
  level:
    root: INFO
    org.springframework.security: INFO
    org.springframework.jdbc.core.JdbcTemplate: DEBUG
  # 如果有写入权限，则会将日志信息写入到如下文件中，默认写10M就会轮换
#  file:
#    path: /var/logs/Taco.log

taco:
  design:
    testProperties: 1