spring:
  application:
    name: email-server
  cloud:
    config:
      uri: http://localhost:8888
server:
  port: 8089

management:
  health:
    jms:
      enabled: off
  endpoints:
    web:
      exposure:
        include: hystrix.stream