tacocloud:
  email:
    host: imap.qq.com
    mailbox: inbox
    username: xxx
    password: look for config on VX

spring:
  main:
    web-application-type: none
  application:
    name: taco-cloud-email

eureka:
  client:
    service-url:
      # 指定Eureka服务器的地址
      defaultZone: http://localhost:8761/eureka/