spring:
  cloud:
    config:
      server:
        git:
          uri: https://gitee.com/fangyuan33/spring-cloud-config
          # 添加配置文件扫描目录
          search-paths: config
  application:
    name: config-server
server:
  port: 8888

eureka:
  client:
    service-url:
      # 指定Eureka服务器的地址
      defaultZone: http://localhost:8761/eureka/
