server:
  port: 0

logging:
  level:
    root: INFO
    # mybatis SQL logger
    tacos.repository.mapper: DEBUG

spring:
  artemis:
    # 注意这里的地址
    broker-url: tcp://xxx:8161
    user: admin
    password: admin
  jms:
    template:
      default-destination: taco-cloud-order-queue
  kafka:
    # 注意这里的地址
    bootstrap-servers: xxx:9092
    consumer:
      group-id: "taco-cloud"

# 用于控制注入使用的消息Bean
mq:
  enable: kafka

artemis:
  orderQueue: taco-cloud-order-queue

kafka:
  orderTopic: taco-cloud-order-topic

eureka:
  client:
    service-url:
      # 指定Eureka服务器的地址
      defaultZone: http://localhost:8761/eureka/