server:
  port: 8080

logging:
  level:
    root: INFO
    # mybatis SQL logger
    tacos.repository.mapper: DEBUG

spring:
  artemis:
    # 注意这里的地址
    broker-url: tcp://xxx:8161
    user: admin
    password: admin
  jms:
    template:
      default-destination: taco-cloud-order-queue

artemis:
  orderQueue: taco-cloud-order-queue