spring:
  datasource:
    type: org.apache.commons.dbcp2.BasicDataSource
    url: jdbc:mysql://localhost:3306/spring_in_action?useUnicode=true&characterEncoding=UTF-8&allowPublicKeyRetrieval=true
    username: root
    # 别把这个提交了
    password: xxxx
    driver-class-name: com.mysql.cj.jdbc.Driver
  sql:
    init:
      data-locations: classpath*:data.sql
      schema-locations: classpath*:schema.sql
      mode: never
  data:
    mongodb:
      host: xxx
      port: 27017
      database: tacocloud